### ISSUE TITLE
Suggestion about perl var names

### ISSUE THREAD

**Issue by 0xAF** [kberov/Slovo#16]
I suggest you to stick to latin letters for variable names.
This way it would be easier for everyone wanting to help with the code.
Variables like **$заглавѥто**, **$дѣсна**, **$ѿговоръ**, etc, could not be easily written in most IDE/Editors. Even if I have Cyrillic keymap installed.

here is a command to find all of these variables (execute it in the root folder of the project):
`grep -RIHnE "\\\$[^a-zA-Z0-9\|\_\=\/\@\"\{\ \(\^\#\!\?\,\.\)]+"`

**Comment by kberov** [comment]
I understand. Yes, I use my own [keymap file in vim](https://github.com/kberov/myvimrc/blob/master/.vim/keymap/old-bulgarian-phonetic.vim) for Old Bulgarian.
I realize not everyone will want to use that keymap file and not everyone uses Vim.
May be I will keep only some very private ones or such that I would prefer explicitly to stand out. Something as a warning.
Thanks for the `grep.`

**Comment by kberov** [comment]
BTW, interesting why I do not get notification emails for issues. May be I have some wrong setting in my profile. Will have to check that too.

**Comment by 0xAF** [comment]
Have you unchecked the "watch" button, on the left side of "star" and "fork" buttons?

**Comment by kberov** [comment]
No, I fixed it. It was an account-wide setting in https://github.com/settings/emails.
I had selected radio-button "Only receive account related emails, and those I subscribe to. "
