### ISSUE TITLE
Fails with Mojo::SQLite 3.003

### ISSUE THREAD

**Issue by andk** [kberov/Slovo#28]
Statistics about the relation between Mojo::SQLite version number and testing success: http://analysis.cpantesters.org/reports_by_field?distv=Slovo-2019.09.19;field=mod%3AMojo%3A%3ASQLite;order=2na

Sample fail report: http://www.cpantesters.org/cpan/report/107981068

**Comment by kberov** [comment]
It seem that this happens as of DBD::SQLite 1.63_05 2019-07-12. Thanks. Fixing it.
